version: "3"

services:
  haraka:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/kubero-dev/haraka:latest
    container_name: haraka
    #restart: always
    #command: tail -f /dev/null
    ports:
      - "8025:8025"
    env_file:
      - .env
    volumes:
      - ./config/tls_cert.pem:/haraka/config/tls_cert.pem
      - ./config/tls_key.pem:/haraka/config/tls_key.pem